version: '3.3'
services: 
  ui-e2e-dev:
    ipc: host
    image: madie
    tty: true
    build: .
    container_name: cydev
    environment:
      - CYPRESS_DEV_USERNAME=${CYPRESS_DEV_USERNAME}
      - CYPRESS_DEV_PASSWORD=${CYPRESS_DEV_PASSWORD}
      - CYPRESS_DEV_ALT_USERNAME=${CYPRESS_DEV_ALT_USERNAME}
      - CYPRESS_DEV_ALT_PASSWORD=${CYPRESS_DEV_ALT_PASSWORD}
      - CYPRESS_TEST_USERNAME=${CYPRESS_TEST_USERNAME}
      - CYPRESS_TEST_PASSWORD=${CYPRESS_TEST_PASSWORD}
      - CYPRESS_TEST_ALT_USERNAME=${CYPRESS_TEST_ALT_USERNAME}
      - CYPRESS_TEST_ALT_PASSWORD=${CYPRESS_TEST_ALT_PASSWORD}
      - CYPRESS_IMPL_USERNAME=${CYPRESS_IMPL_USERNAME}
      - CYPRESS_IMPL_PASSWORD=${CYPRESS_IMPL_PASSWORD}
      - CYPRESS_IMPL_ALT_USERNAME=${CYPRESS_IMPL_ALT_USERNAME}
      - CYPRESS_IMPL_ALT_PASSWORD=${CYPRESS_IMPL_ALT_PASSWORD}
      - CYPRESS_VSAC_API_KEY=${CYPRESS_VSAC_API_KEY}
      - CYPRESS_DEV_MADIE_CLIENTID=${CYPRESS_DEV_MADIE_CLIENTID}
      - CYPRESS_DEV_MADIE_CODECHALLENGE=${CYPRESS_DEV_MADIE_CODECHALLENGE}
      - CYPRESS_DEV_MADIE_REDIRECTURI=${CYPRESS_DEV_MADIE_REDIRECTURI}
      - CYPRESS_DEV_MADIE_AUTHURI=${CYPRESS_DEV_MADIE_AUTHURI}
      - CYPRESS_MADIE_CODEVERIFIER=${CYPRESS_MADIE_CODEVERIFIER}
      - CYPRESS_TEST_MADIE_CLIENTID=${CYPRESS_TEST_MADIE_CLIENTID}
      - CYPRESS_TEST_MADIE_REDIRECTURI=${CYPRESS_TEST_MADIE_REDIRECTURI}
      - CYPRESS_TEST_MADIE_AUTHURI=${CYPRESS_TEST_MADIE_AUTHURI}
      - CYPRESS_IMPL_MADIE_CLIENTID=${CYPRESS_IMPL_MADIE_CLIENTID}
      - CYPRESS_IMPL_MADIE_REDIRECTURI=${CYPRESS_IMPL_MADIE_REDIRECTURI}
      - CYPRESS_IMPL_MADIE_AUTHURI=${CYPRESS_IMPL_MADIE_AUTHURI}
      - NODE_OPTIONS=${NODE_OPTIONS}
      - CYPRESS_DEV_MEASURESHARING_API_KEY=${CYPRESS_DEV_MEASURESHARING_API_KEY}
      - CYPRESS_TEST_MEASURESHARING_API_KEY=${CYPRESS_TEST_MEASURESHARING_API_KEY}
      - CYPRESS_IMPL_MEASURESHARING_API_KEY=${CYPRESS_IMPL_MEASURESHARING_API_KEY}

    volumes:
      - ./mochawesome-report:/app/mochawesome-report
